name: Build Snap Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Snapcraft
        uses: snapcore/action-build@v1

      - name: Build snap
        run: |
          snapcraft --destructive-mode

      - name: Upload Snap Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pslabel-gateway-ui-snap
          path: ./*.snap
