name: Build Snap Package for RPI4

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    name: Build ARM64 Snap for RPI4

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU for cross-compilation
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Snapcraft
        run: |
          sudo snap install snapcraft --classic
          sudo snap install lxd
          sudo lxd init --auto

      - name: Build ARM64 snap
        run: |
          snapcraft --destructive-mode --build-for=arm64
        env:
          SNAPCRAFT_BUILD_ENVIRONMENT: host

      - name: Rename snap for clarity
        run: |
          mv *.snap pslabel-t3-rpi4-arm64.snap

      - name: Upload ARM64 Snap Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pslabel-t3-rpi4-arm64
          path: pslabel-t3-rpi4-arm64.snap
          retention-days: 30
